- name: Hello World Sample
  hosts: all
  # Secrets
  vars_files:
    - 'vault.yml'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Display Secret
      debug:
        msg: "{{ secret_data }}"
