---
-
  name: Display content of hosts
  hosts: [multi]
  tasks:
    - name: Display hosts contents
      command: cat hosts chdir=/etc
      register: command_output

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"
